create extension if not exists "pgcrypto";

grant usage on schema public to anon, authenticated;

create table if not exists public.profile_roles (
	id bigint generated by default as identity primary key,
	code text not null unique,
	label text not null,
	created_at timestamptz not null default now()
);

insert into public.profile_roles (code, label)
values
	('admin', 'Admin'),
	('mod', 'Moderator'),
	('normal', 'Normal'),
	('sponsor', 'Sponsor'),
	('professional', 'Professional'),
	('artist', 'Artist'),
	('influencer', 'Influencer'),
	('factory', 'Factory'),
	('business', 'Business'),
	('company', 'Company')
on conflict (code) do update set label = excluded.label;

grant select on table public.profile_roles to anon, authenticated;

create table if not exists public.profiles (
	id uuid primary key references auth.users(id) on delete cascade,
	username text not null unique,
	email text unique,
	name text,
	description text,
	title text,
	role_id bigint not null references public.profile_roles(id),
	dedication text,
	avatar_url text,
	followers_count integer not null default 0,
	following_count integer not null default 0,
	videos_count integer not null default 0,
	likes_count integer not null default 0,
	saved_videos_count integer not null default 0,
	liked_videos_count integer not null default 0,
	sponsored_by text[] not null default '{}',
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists name text;
alter table public.profiles add column if not exists description text;
alter table public.profiles add column if not exists title text;
alter table public.profiles add column if not exists role text;
alter table public.profiles add column if not exists role_id bigint;
alter table public.profiles add column if not exists dedication text;
alter table public.profiles add column if not exists followers_count integer not null default 0;
alter table public.profiles add column if not exists following_count integer not null default 0;
alter table public.profiles add column if not exists videos_count integer not null default 0;
alter table public.profiles add column if not exists likes_count integer not null default 0;
alter table public.profiles add column if not exists saved_videos_count integer not null default 0;
alter table public.profiles add column if not exists liked_videos_count integer not null default 0;
alter table public.profiles add column if not exists sponsored_by text[] not null default '{}';
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

do $$
begin
	if not exists (
		select 1
		from pg_constraint
		where conname = 'profiles_role_id_fkey'
			and conrelid = 'public.profiles'::regclass
	) then
		alter table public.profiles
			add constraint profiles_role_id_fkey
			foreign key (role_id) references public.profile_roles(id);
	end if;
end $$;

update public.profiles p
set role_id = r.id
from public.profile_roles r
where p.role_id is null
	and r.code = case lower(coalesce(p.role, 'normal'))
		when 'customer' then 'normal'
		when 'moderator' then 'mod'
		when 'business' then 'business'
		else lower(coalesce(p.role, 'normal'))
	end;

update public.profiles
set role_id = (select id from public.profile_roles where code = 'normal')
where role_id is null;

create or replace function public.default_profile_role_id()
returns bigint
language sql
stable
as $$
	select id from public.profile_roles where code = 'normal' limit 1;
$$;

alter table public.profiles alter column role_id set default public.default_profile_role_id();
alter table public.profiles alter column role_id set not null;

do $$
begin
	if exists (
		select 1
		from pg_constraint
		where conname = 'profiles_role_check'
			and conrelid = 'public.profiles'::regclass
	) then
		alter table public.profiles drop constraint profiles_role_check;
	end if;
end $$;

create unique index if not exists profiles_email_key on public.profiles(email) where email is not null;

grant select, insert, update, delete on table public.profiles to authenticated;
grant select on table public.profiles to anon;

create table if not exists public.videos (
	id uuid primary key default gen_random_uuid(),
	user_id uuid not null references auth.users(id) on delete cascade,
	video_url text not null,
	title text not null,
	created_at timestamptz not null default now()
);

grant select, insert, update, delete on table public.videos to authenticated;
grant select on table public.videos to anon;

create table if not exists public.notifications (
	id uuid primary key default gen_random_uuid(),
	user_id uuid not null references auth.users(id) on delete cascade,
	message text not null,
	read boolean not null default false,
	created_at timestamptz not null default now()
);

grant select, insert, update, delete on table public.notifications to authenticated;

create table if not exists public.video_likes (
	id uuid primary key default gen_random_uuid(),
	user_id uuid not null references auth.users(id) on delete cascade,
	video_id uuid not null references public.videos(id) on delete cascade,
	created_at timestamptz not null default now(),
	unique(user_id, video_id)
);

grant select, insert, delete on table public.video_likes to authenticated;
grant select on table public.video_likes to anon;

create table if not exists public.saved_videos (
	id uuid primary key default gen_random_uuid(),
	user_id uuid not null references auth.users(id) on delete cascade,
	video_id uuid not null references public.videos(id) on delete cascade,
	created_at timestamptz not null default now(),
	unique(user_id, video_id)
);

grant select, insert, delete on table public.saved_videos to authenticated;

create table if not exists public.follows (
	follower_id uuid not null references auth.users(id) on delete cascade,
	following_id uuid not null references auth.users(id) on delete cascade,
	created_at timestamptz not null default now(),
	primary key (follower_id, following_id),
	check (follower_id <> following_id)
);

grant select, insert, delete on table public.follows to authenticated;
grant select on table public.follows to anon;

alter table public.profiles enable row level security;
alter table public.profile_roles enable row level security;
alter table public.videos enable row level security;
alter table public.notifications enable row level security;
alter table public.video_likes enable row level security;
alter table public.saved_videos enable row level security;
alter table public.follows enable row level security;

drop policy if exists "Roles are publicly readable" on public.profile_roles;
create policy "Roles are publicly readable"
on public.profile_roles
for select
using (true);

drop policy if exists "Public profiles are readable" on public.profiles;
create policy "Public profiles are readable"
on public.profiles
for select
using (true);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can delete own profile" on public.profiles;
create policy "Users can delete own profile"
on public.profiles
for delete
to authenticated
using (auth.uid() = id);

drop policy if exists "Videos are publicly readable" on public.videos;
create policy "Videos are publicly readable"
on public.videos
for select
using (true);

drop policy if exists "Authenticated users can upload own videos" on public.videos;
create policy "Authenticated users can upload own videos"
on public.videos
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own videos" on public.videos;
create policy "Users can update own videos"
on public.videos
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own videos" on public.videos;
create policy "Users can delete own videos"
on public.videos
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read own notifications" on public.notifications;
create policy "Users can read own notifications"
on public.notifications
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can update own notifications" on public.notifications;
create policy "Users can update own notifications"
on public.notifications
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can insert own notifications" on public.notifications;
create policy "Users can insert own notifications"
on public.notifications
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own notifications" on public.notifications;
create policy "Users can delete own notifications"
on public.notifications
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Video likes are publicly readable" on public.video_likes;
create policy "Video likes are publicly readable"
on public.video_likes
for select
using (true);

drop policy if exists "Users can like videos as themselves" on public.video_likes;
create policy "Users can like videos as themselves"
on public.video_likes
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can unlike videos as themselves" on public.video_likes;
create policy "Users can unlike videos as themselves"
on public.video_likes
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read own saved videos" on public.saved_videos;
create policy "Users can read own saved videos"
on public.saved_videos
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can save videos as themselves" on public.saved_videos;
create policy "Users can save videos as themselves"
on public.saved_videos
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can unsave videos as themselves" on public.saved_videos;
create policy "Users can unsave videos as themselves"
on public.saved_videos
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Follows are publicly readable" on public.follows;
create policy "Follows are publicly readable"
on public.follows
for select
using (true);

drop policy if exists "Users can follow as themselves" on public.follows;
create policy "Users can follow as themselves"
on public.follows
for insert
to authenticated
with check (auth.uid() = follower_id);

drop policy if exists "Users can unfollow as themselves" on public.follows;
create policy "Users can unfollow as themselves"
on public.follows
for delete
to authenticated
using (auth.uid() = follower_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = now();
	return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

create or replace function public.update_profile_video_count()
returns trigger
language plpgsql
as $$
begin
	if tg_op = 'INSERT' then
		update public.profiles set videos_count = videos_count + 1 where id = new.user_id;
		return new;
	elsif tg_op = 'DELETE' then
		update public.profiles set videos_count = greatest(videos_count - 1, 0) where id = old.user_id;
		-- Video delete can cascade likes; recompute received likes from remaining videos.
		update public.profiles p
		set likes_count = (
			select count(*)::int
			from public.video_likes vl
			join public.videos v on v.id = vl.video_id
			where v.user_id = old.user_id
		)
		where p.id = old.user_id;
		return old;
	end if;

	return null;
end;
$$;

drop trigger if exists videos_profile_counter_trg on public.videos;
create trigger videos_profile_counter_trg
after insert or delete on public.videos
for each row execute function public.update_profile_video_count();

create or replace function public.update_profile_saved_video_count()
returns trigger
language plpgsql
as $$
begin
	if tg_op = 'INSERT' then
		update public.profiles set saved_videos_count = saved_videos_count + 1 where id = new.user_id;
		return new;
	elsif tg_op = 'DELETE' then
		update public.profiles
		set saved_videos_count = greatest(saved_videos_count - 1, 0)
		where id = old.user_id;
		return old;
	end if;

	return null;
end;
$$;

drop trigger if exists saved_videos_profile_counter_trg on public.saved_videos;
create trigger saved_videos_profile_counter_trg
after insert or delete on public.saved_videos
for each row execute function public.update_profile_saved_video_count();

create or replace function public.update_profile_follow_counts()
returns trigger
language plpgsql
as $$
begin
	if tg_op = 'INSERT' then
		update public.profiles set following_count = following_count + 1 where id = new.follower_id;
		update public.profiles set followers_count = followers_count + 1 where id = new.following_id;
		return new;
	elsif tg_op = 'DELETE' then
		update public.profiles
		set following_count = greatest(following_count - 1, 0)
		where id = old.follower_id;
		update public.profiles
		set followers_count = greatest(followers_count - 1, 0)
		where id = old.following_id;
		return old;
	end if;

	return null;
end;
$$;

drop trigger if exists follows_profile_counter_trg on public.follows;
create trigger follows_profile_counter_trg
after insert or delete on public.follows
for each row execute function public.update_profile_follow_counts();

create or replace function public.update_profile_like_counts()
returns trigger
language plpgsql
as $$
declare
	v_video_owner uuid;
begin
	if tg_op = 'INSERT' then
		select v.user_id into v_video_owner from public.videos v where v.id = new.video_id;

		update public.profiles set liked_videos_count = liked_videos_count + 1 where id = new.user_id;

		if v_video_owner is not null then
			update public.profiles set likes_count = likes_count + 1 where id = v_video_owner;
		end if;

		return new;
	elsif tg_op = 'DELETE' then
		select v.user_id into v_video_owner from public.videos v where v.id = old.video_id;

		update public.profiles
		set liked_videos_count = greatest(liked_videos_count - 1, 0)
		where id = old.user_id;

		if v_video_owner is not null then
			update public.profiles
			set likes_count = greatest(likes_count - 1, 0)
			where id = v_video_owner;
		end if;

		return old;
	end if;

	return null;
end;
$$;

drop trigger if exists video_likes_profile_counter_trg on public.video_likes;
create trigger video_likes_profile_counter_trg
after insert or delete on public.video_likes
for each row execute function public.update_profile_like_counts();

create or replace function public.refresh_profile_counters(target_user_id uuid default null)
returns void
language sql
as $$
	update public.profiles p
	set
		videos_count = (
			select count(*)::int
			from public.videos v
			where v.user_id = p.id
		),
		followers_count = (
			select count(*)::int
			from public.follows f
			where f.following_id = p.id
		),
		following_count = (
			select count(*)::int
			from public.follows f
			where f.follower_id = p.id
		),
		saved_videos_count = (
			select count(*)::int
			from public.saved_videos sv
			where sv.user_id = p.id
		),
		liked_videos_count = (
			select count(*)::int
			from public.video_likes vl
			where vl.user_id = p.id
		),
		likes_count = (
			select count(*)::int
			from public.video_likes vl
			join public.videos v on v.id = vl.video_id
			where v.user_id = p.id
		)
	where target_user_id is null or p.id = target_user_id;
$$;

create or replace function public.get_videos_feed(p_limit integer default 30)
returns table (
	id uuid,
	user_id uuid,
	title text,
	video_url text,
	created_at timestamptz,
	username text,
	avatar_url text
)
language sql
stable
as $$
	select
		v.id,
		v.user_id,
		v.title,
		v.video_url,
		v.created_at,
		p.username,
		p.avatar_url
	from public.videos v
	left join public.profiles p on p.id = v.user_id
	order by v.created_at desc
	limit greatest(coalesce(p_limit, 30), 1);
$$;

grant execute on function public.get_videos_feed(integer) to anon, authenticated;

insert into storage.buckets (id, name, public)
values ('game-clips', 'game-clips', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can read game clips" on storage.objects;
create policy "Public can read game clips"
on storage.objects
for select
using (bucket_id = 'game-clips');

drop policy if exists "Authenticated users can upload game clips" on storage.objects;
create policy "Authenticated users can upload game clips"
on storage.objects
for insert
to authenticated
with check (
	bucket_id = 'game-clips'
	and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users can update own game clips" on storage.objects;
create policy "Users can update own game clips"
on storage.objects
for update
to authenticated
using (
	bucket_id = 'game-clips'
	and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
	bucket_id = 'game-clips'
	and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users can delete own game clips" on storage.objects;
create policy "Users can delete own game clips"
on storage.objects
for delete
to authenticated
using (
	bucket_id = 'game-clips'
	and (storage.foldername(name))[1] = auth.uid()::text
);

do $$
declare
	v_user_id uuid;
	v_instance_id uuid;
	v_email text := 'erickgiber7@gmail.com';
	v_password text := 'ChangeMe.Admin.2026!';
begin
	select coalesce(
		(select id from auth.instances limit 1),
		'00000000-0000-0000-0000-000000000000'::uuid
	) into v_instance_id;

	select id into v_user_id from auth.users where email = v_email;

	if v_user_id is null then
		v_user_id := gen_random_uuid();

		insert into auth.users (
			instance_id,
			id,
			aud,
			role,
			email,
			encrypted_password,
			email_confirmed_at,
			raw_app_meta_data,
			raw_user_meta_data,
			is_super_admin,
			is_sso_user,
			is_anonymous,
			created_at,
			updated_at,
			confirmation_token,
			email_change,
			email_change_token_new,
			recovery_token
		)
		values (
			v_instance_id,
			v_user_id,
			'authenticated',
			'authenticated',
			v_email,
			crypt(v_password, gen_salt('bf')),
			now(),
			'{"provider":"email","providers":["email"],"role":"admin"}'::jsonb,
			jsonb_build_object('name', 'Erick Ramirez', 'username', 'erickgiber'),
			false,
			false,
			false,
			now(),
			now(),
			'',
			'',
			'',
			''
		);
	end if;

	update auth.users
	set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) || jsonb_build_object('role', 'admin')
	where id = v_user_id;

	insert into auth.identities (
		id,
		user_id,
		identity_data,
		provider,
		provider_id,
		created_at,
		updated_at,
		last_sign_in_at
	)
	values (
		gen_random_uuid(),
		v_user_id,
		jsonb_build_object('sub', v_user_id::text, 'email', v_email),
		'email',
		v_email,
		now(),
		now(),
		now()
	)
	on conflict do nothing;

	insert into public.profiles (
		id,
		username,
		email,
		name,
		description,
		title,
		role_id,
		dedication,
		avatar_url,
		sponsored_by
	)
	values (
		v_user_id,
		'erickgiber',
		'erickgiber7@gmail.com',
		'Erick Ramirez',
		'🎮 Radiant League of Legends Player | 🏆 Tournament Champion | 📺 Streaming Daily',
		'Professional Esports Player',
		(select id from public.profile_roles where code = 'admin' limit 1),
		'Content Creator',
		'https://i.ibb.co/MkfnJMF/c626c26ad861.jpg',
		array['ESPN Esports', 'Red Bull', 'Logitech G']
	)
	on conflict (id) do update set
		username = excluded.username,
		email = excluded.email,
		name = excluded.name,
		description = excluded.description,
		title = excluded.title,
		role_id = (select id from public.profile_roles where code = 'admin' limit 1),
		dedication = excluded.dedication,
		avatar_url = excluded.avatar_url,
		sponsored_by = excluded.sponsored_by,
		updated_at = now();

	perform public.refresh_profile_counters(v_user_id);
end $$;
